---

## server1 is wireguard1 which serves VPN for clients
- hosts: server1
  remote_user: wireguard1
  become: yes
  become_method: sudo
  connection: ssh
  roles:
    - install_wireguard


## server2 is connected to the lan inside
- hosts: server2
  remote_user: wireguard2
  become: yes
  roles:
    - install_wireguard

# client test
- hosts: client1
  remote_user: client
  become: yes
  vars:
    test: this is a test
  tasks:
    - name: test running with login user pass
      shell: echo hello zerobits01 > /tmp/something
    - debug: msg="Hello from {{ inventory_hostname }}!"

# inner servers config if needed
- hosts: webserver
  remote_user: zerobits
  become: yes
  tasks:
    - name: touch a file in /tmp
      file:
        path: /tmp/ansible-task-sample
        state: touch
        mode: 0644